name: Upload with Approval

on:
  push:
    paths:
      - 'frontend/**'
      - 'backend/**'

jobs:
  request-approval:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Wait for owner approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: rajmohanbharathi
          issue-title: "Approve file upload to S3"
          issue-body: "Please approve to proceed with uploading the file to S3."

  upload-to-s3:
    needs: request-approval
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Pythonß
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install boto3 flask

      - name: Upload file to S3
        run: python backend/upload_to_s3.py
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BUCKET_NAME: ${{ secrets.S3_BUCKET }}